# Generated by Django 4.0 on 2021-12-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='election',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTI_CHOICE', 'Multi Choice'), ('RANKED_CHOICE', 'Ranked Choice'), ('INSTANT_RUNOFF', 'Instant Runoff'), ('SINGLE_TRANSFER', 'Single Transfer')], default='SINGLE_CHOICE', max_length=15),
        ),
        migrations.AddField(
            model_name='election',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='result_type',
            field=models.CharField(choices=[('CURRENT_RESULT', 'Current Result'), ('AFTER_VOTING', 'After Voting'), ('AFTER_ELECTION', 'After Election')], default='CURRENT_RESULT', max_length=14),
        ),
        migrations.AddField(
            model_name='election',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ElectionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
                ('sent_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('candidate_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.candidategroup')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
