# Generated by Django 4.0 on 2021-12-17 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0002_candidategroup_rename_owner_election_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='linked_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
