# Generated by Django 4.0 on 2021-12-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_candidate_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='election'),
        ),
    ]
