# Generated by Django 4.0 on 2021-12-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('election', '0004_alter_election_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='linked_user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='linked_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
    ]
