# Generated by Django 4.0 on 2021-12-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_remove_candidate_linked_user_candidate_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.candidategroup'),
        ),
    ]
