# Generated by Django 4.0 on 2021-12-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '__first__'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('candidate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidategroup')),
                ('linked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
