# Generated by Django 4.0 on 2021-12-31 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='owned_by',
            new_name='owned_by_election',
        ),
    ]
